forge 'forge.puppetlabs.com'

# Forge Modules
mod 'camptocamp/accounts'
mod 'domcleal/foreman_data_binding'
mod 'nvogel/ansible'
mod 'puppetlabs/concat'
mod 'puppetlabs/firewall'
mod 'puppetlabs/inifile'
mod 'puppetlabs/java_ks'
mod 'puppetlabs/lvm'
mod 'puppetlabs/ntp'
mod 'puppetlabs/stdlib'
mod 'spiette/selinux'
mod 'theforeman/concat_native'
mod 'theforeman/puppet'
mod 'thias/sysctl'